### ISSUE TITLE
Føj markedAsDeleted til default scope for Review

### ISSUE THREAD

**Issue by jacobandresen** [DBCDK/dbc-community-service#11]
Iøjeblikket skal vi aktivt tilføje markedAsDeleted:null til filtre for at finde reviews der ikke er slettet. En bedre løsning er at tilføje det til default scope i review.json .  (Se kommentar i https://github.com/DBCDK/biblo/pull/189 )

**Comment by jacobandresen** [comment]
se evt https://github.com/DBCDK/dbc-community-service/pull/22/commits/d0ffdaa8579c81314bda1e7e05d3998928d681fb

**Comment by vibjerg** [comment]
ikke relevant længere
