### ISSUE TITLE
possible EventEmitter memory leak - får byggejobbet til at fejle

### ISSUE THREAD

**Issue by KiraH** [DBCDK/dbc-community-service#20]
Byggejobbet fejler pga nedenstående besked:

13:47:21 -- Logs begin at Sun 2016-08-21 13:13:10 CEST, end at Tue 2016-08-23 13:47:21 CEST. --
13:47:21 Aug 23 13:47:05 biblo_community-udv.service[7470]: (node:7470) Warning: Possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit
13:47:21 Aug 23 13:47:05 biblo_community-udv.service[7470]: (node:7470) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by vibjerg** [comment]
https://github.com/DBCDK/dbc-community-service/pull/21 will quickfix the problem
