### ISSUE TITLE
Sletning af profil

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/dbc-community-service#91]
Det skal være muligt at slette en profil og alle data som er relateret til profilen. 

- [x] Profile 
- [x] Groups
- [x] Posts
- [x] Comments
- [x] Likes
- [x] Flags
- [x] Alle uploadede billeder skal fjernes

**Comment by AndersFriisBrodsgaard** [comment]
Feedback:
- Jeg sletter min testprofil og overfører ejerskab en min gruppe til en moderator, står der 0 følgere ud for gruppen på gruppeoversigtssiden, mens jeg stadig står som ejer inde på gruppesiden og som eneste følger. 
Efter overførsel af en gruppe, hvor kun jeg er følger, skal der være én følger, dvs. den profil, som gruppen er overdraget til. Og min profil skal ikke optræde længere med billede eller lign.
